encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path('wiki/<str:entry>', views.entry, name="entry"),
    path('results',views.results, name='results'),
    path('create', views.create, name='create'),
    path('edit/<str:page>', views.edit, name='edit'),
    path('random', views.random, name='random')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from . import util
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from os.path import exists
from random import randint
from django import forms


# View for home page
def index(request):
    all_entries = sorted(util.list_entries())
    return render(request, "encyclopedia/index.html", {
        "entries": all_entries
    })

# View for a particular entry
def entry(request, entry):
    # Check if entry exists, if it does:
    if util.entryexists(entry):
        # Convert the content into html
        html = util.convert(entry)
        # Get entry title
        all_entries = util.list_entries()
        title = [e for e in all_entries if entry.lower()==e.lower()]
        # Render the entry's html page
        return render(request, f"encyclopedia/entry.html",{
            'title': title[0],
            'content': html
            })
    
    else: 
        # Present an error page:
        return HttpResponse(f"Sorry, {entries} page does not exist.")

# View for search results: 
def results(request):
    entrylist_normal = util.list_entries()
    entrylist_lower = [i.lower() for i in entrylist_normal]
    # If this was a search query
    search_item = request.POST['search']
    # Check if an entry exists. If there's an EXACT match,
    if util.entryexists(search_item):
        # Then, redirect the user to the entry page.
        return HttpResponseRedirect(reverse('encyclopedia:entry', args=(search_item,))) 
    
    # Else, if the entry does not exist,
    else:
        # Find similar entries
        results = []
        for index, item in enumerate(entrylist_lower):
            # If the search is a substring of an entry, we will show it on the results page
            if len(item.split(search_item.lower()))>1:
                results.append(entrylist_normal[index])
        # Now, show(render) the results page.
        return render(request, 'encyclopedia/result.html', {
            'results':results
            })

# Create a new entry
def create(request):
    # If the POST request was sent (aka entry created)
    if request.method == 'POST':
        # Get the title and content of the post
        title = request.POST['Title']
        content = request.POST['Content']
        # Carry out data-validation (make sure entry does not already exist)
        if not util.entryexists(title):
            # If entry doesn't exist, write and save a md file
            util.save_entry(title,content)
            # Redirect user to the entry page created
            return HttpResponseRedirect(reverse('encyclopedia:entry', args=(title,)))

        # Else, if the entry already exists  
        else:
            # Return an error message
            return render(request,"encyclopedia/create.html",{
                'Error_Message':'ERROR: This entry already exists.'
                })

    # If it's a GET request to view the form page to create a new entry, render the form:
    return render(request,"encyclopedia/create.html")

def edit(request,page):
    # POST request: an edit was submitted
    if request.method == 'POST':
        # Replace the markdown file with the new content.
        content = request.POST['content'] 
        util.save_entry(page.capitalize(),content) 
        # Redirect user back to the entry page to see the update
        return HttpResponseRedirect(reverse('encyclopedia:entry', args=(page,)))
    
    # Else, if it's a GET request to view the edit page
    else:
        # Populate the textarea with the entry's existing content
         with open(f"entries/{page}.md",'r') as f:
            text=f.read()
        # Render the view 
         return render(request,"encyclopedia/edit.html",{
            'entry_title': page,
            'entry_content': text
            })

# Direct users to a random entry
def random(request):
    pick_index = randint(0,len(util.list_entries())-1)
    entry_name=util.list_entries()[pick_index]
    #Redirect to the random page
    return HttpResponseRedirect(reverse('encyclopedia:entry', args=(entry_name,)))









            

encyclopedia/templates/encyclopedia/create.html
<!-- File is used to create new entries -->
<!-- Variables used in this html: results (filters) -->

{% extends "encyclopedia/layout.html" %}

{% block body %}
<h2 id='heading'>Create New Entry</h2>

<form action="{% url 'encyclopedia:create' %}" method='post'>
    {% csrf_token %}
    <p id='error'>{{ Error_Message }}</p>
    <b>Entry Title:</b> <br>
    <input type="text" name="Title" placeholder="Type here..."> 
    <br><br>
    <b>Content:</b> <br>
    <textarea name='Content' placeholder='Type here...'></textarea>
    <br><br>
    <input type="submit" value="Save">
</form>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
<!-- File is used to create new entries -->
<!-- Variables used in this html: results (filters) -->

{% extends "encyclopedia/layout.html" %}

{% block body %}
<h2 id='heading'>{{ entry_title }}</h2>
<br>
<form action="{% url 'encyclopedia:edit' entry_title %}" method='post'>
    {% csrf_token %}
    <textarea name='content' rows="4" cols="50">{{ entry_content }}</textarea>
    <br><br>
    <input type="submit" value="Save">
</form>


{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block nav %}  
<a href="{% url 'encyclopedia:edit' title %}">
    Edit Entry
</a>
{% endblock %}

{% block body %}
<h2 id='heading'>{{ title }}</h2>
<p id='subtext'>From Wikipedia, the free encyclopedia</p>

{{ content|safe }}

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block body %}
<h2 id='heading'>All Pages</h2>

<ul>
    {% for entry in entries %}
        <li><a href="{% url 'encyclopedia:entry' entry %}"> {{ entry }} </a></li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Wiki</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'encyclopedia/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'encyclopedia/favicon-32x32.png' %} ">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'encyclopedia/favicon-16x16.png' %} ">
    </head>
    <body>
        <div class="row-updated">
            <div class="sidebar">
                <div class='sidebar-content'>
                    <a href="{% url 'encyclopedia:index' %}">
                        <img id='logo' src='https://upload.wikimedia.org/wikipedia/en/thumb/3/31/Puzzlesphere-ps-realign-letters-plus-bold-test.svg/523px-Puzzlesphere-ps-realign-letters-plus-bold-test.svg.png'>
                    </a>
                    <hr>
                    <div id='sidebar-buttons'>
                        <div>
                            <a href="{% url 'encyclopedia:index' %}">Home</a>
                        </div>
                        <div>
                            <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                        </div>
                        <div>
                            <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="main">
                <div id='top'>
                    <div class="nav" id='edit'>
                        {% block nav %} {% endblock %}
                    </div>
                    <form action="{% url 'encyclopedia:results' %}" method='POST'>
                        {% csrf_token %}
                        <input id="search" type="text" name="search" placeholder="Search Encyclopedia">
                    </form>
                </div>
                <div id = 'content'>
                    {% block body %}
                    {% endblock %}
                </div>       
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/result.html
<!-- Variables used in this html: results (filters) -->

{% extends "encyclopedia/layout.html" %}

{% block body %}

<h2 id='heading'>Search Results</h2>

<ul>
    {% for r in results %} 
        <li><a href="{% url 'encyclopedia:entry' r %}"> {{ r }} </a></li>
    {% empty %}
        Sorry, we don't have what you're looking for. 
        <a href="{% url 'encyclopedia:index' %}">Return to home page?</a>
    {% endfor %}
</ul>

{% endblock %}